---
application:
  name: "jam-in-a-band-camp"
  project: "Jam in the Band Camp"
  organization: "QoveryCommunity"
routers:
- name: "main-jam-in-a-band-camp"
  routes:
  - application_name: "jam-in-a-band-camp"
    paths:
    - "/*"
